import tkinter
from tkinter import*
from tkinter import ttk
from tkinter import messagebox
import mysql.connector
j = tkinter.Tk()
j.title("https://www.irctc.co.in")
j.geometry('1920x1080')
j.iconbitmap(r"railwayico.ico")
bg=tkinter.PhotoImage(file=r"regi.png")
frm=tkinter.Frame(j)
frm.place(x=75,y=0,height=5000,width=5000)
lab=tkinter.Label(frm,image=bg)
lab.place(x=0,y=0)

ft1=tkinter.Label(j,text='NEW USER REGISTRATION',font=('Georgia',50,'bold'),bg='white',fg='orange')
ft1.place(x=185,y=15)

fn=tkinter.Label(j,text='FIRST NAME',font=('Georgia',20,'bold'),bg='white',fg='orange')
fn.place(x=100,y=140)
e1=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e1.place(x=325,y=140)
ln=tkinter.Label(j,text='LAST NAME',font=('Georgia',20,'bold'),bg='white',fg='orange')
ln.place(x=725,y=140)
e2=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e2.place(x=950,y=140)

ml=tkinter.Label(j,text='E-MAIL',font=('Georgia',20,'bold'),bg='white',fg='orange')
ml.place(x=100,y=220)
e3=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e3.place(x=325,y=220)
ph=tkinter.Label(j,text='MOBILE',font=('Georgia',20,'bold'),bg='white',fg='orange')
ph.place(x=725,y=220)
e4=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e4.place(x=950,y=220)

us=tkinter.Label(j,text='USED ID',font=('Georgia',20,'bold'),bg='white',fg='orange')
us.place(x=100,y=300)
e5=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e5.place(x=325,y=300)
ad=tkinter.Label(j,text='ADDRESS',font=('Georgia',20,'bold'),bg='white',fg='orange')
ad.place(x=725,y=300)
e6=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e6.place(x=950,y=300)

nc=tkinter.Label(j,text='NEW CODE',font=('Georgia',20,'bold'),bg='white',fg='orange')
nc.place(x=100,y=380)
e7=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e7.place(x=325,y=380)
cc=tkinter.Label(j,text='RE-ENTER',font=('Georgia',20,'bold'),bg='white',fg='orange')
cc.place(x=725,y=380)
e8=tkinter.Entry(j,width = 15,font=('Georgia',20,'bold'),bg='white',fg='black')
e8.place(x=950,y=380)

def bala():
    a=e1.get()
    b=e2.get()
    c=e3.get()
    d=(int(e4.get()))
    e=e5.get()
    f=e6.get()
    g=e7.get()
    h=e8.get()
    db=mysql.connector.connect(host='localhost',user='root',db='introir1')
    cur=db.cursor()
    cur.execute("insert into google01 values('%s','%s','%s',%d,'%s','%s','%s','%s')"%(a,b,c,d,e,f,g,h))
    db.commit()
    messagebox.showinfo("IRCTC STATUS","REGISTERED SUCCESSFULLY")
bt1=tkinter.Button(j,text='CREATE ACCOUNT',width = 15,font=('Georgia',20,'bold'),command = bala,bg='white',fg='black')
bt1.place(x=300,y=500)

def rj():
    e1.delete(0,"end")
    e2.delete(0,"end")
    e3.delete(0,"end")
    e4.delete(0,"end")
    e5.delete(0,"end")
    e6.delete(0,"end")
    e7.delete(0,"end")
    e8.delete(0,"end")
    e1.focus()
    j.destroy()
    import irctcintro
bt2=tkinter.Button(j,text='BOOK TICKET',width = 15,font=('Georgia',20,'bold'),command = rj,bg='white',fg='black')
bt2.place(x=750,y=500)
